/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios.Principal;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import libraries.formularios.libLogin;

/**
 *
 * @author Ellet
 */
public class Login extends javax.swing.JFrame {
    int contador = 0;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botlog = new javax.swing.JButton();
        txtusername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        botsal = new javax.swing.JButton();
        lbimagenfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SDMT - LOGIN");
        setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel1.setText("USERNAME");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 41, -1, -1));

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel2.setText("PASSWORD");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 85, -1, -1));

        botlog.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        botlog.setText("LOGIN");
        botlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botlogActionPerformed(evt);
            }
        });
        getContentPane().add(botlog, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 134, 121, 33));

        txtusername.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 38, 111, -1));

        jLabel3.setBackground(getBackground());
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/rsz_loginmejorado.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 100, 100));

        txtpassword.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        txtpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpasswordKeyPressed(evt);
            }
        });
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 82, 111, -1));

        botsal.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        botsal.setText("SALIR");
        botsal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botsalActionPerformed(evt);
            }
        });
        getContentPane().add(botsal, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 134, 121, 33));

        lbimagenfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/rsz_login.jpg"))); // NOI18N
        lbimagenfondo.setText(" ");
        getContentPane().add(lbimagenfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botlogActionPerformed
        AccionLogin();
    }//GEN-LAST:event_botlogActionPerformed

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void botsalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botsalActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botsalActionPerformed

    private void txtpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyPressed
        char e = evt.getKeyChar();
        if(e == KeyEvent.VK_ENTER){
            AccionLogin();
        }
    }//GEN-LAST:event_txtpasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    
    public void AccionLogin(){
        if(new libLogin().ComprobarLogin()){
            JOptionPane.showMessageDialog(null, "BIENVENIDO " + txtusername.getText().toUpperCase(),"WELCOME!",JOptionPane.INFORMATION_MESSAGE);
            new Principal().setVisible(true);
            this.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(null,"USUARIO O CONTRASEÑA INCORRECTA","ACCESS DENIED",JOptionPane.ERROR_MESSAGE);
            this.contador++;
            if((contador % 3) == 0 && contador != 0){
                new libLogin().LoginTimer();
                JOptionPane.showMessageDialog(null,"HA EXCEDIDO EL MAXIMO DE INTENTOS PERMITIDOS, POR FAVOR ESPERE 30 SEGUNDOS","ACCESS DENIED",JOptionPane.ERROR_MESSAGE);
            }
            txtpassword.setText("");
            
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton botlog;
    public static javax.swing.JButton botsal;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbimagenfondo;
    public static javax.swing.JPasswordField txtpassword;
    public static javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
