/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios.Principal;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.Timer;


/**
 *
 * @author Ellet
 */
public class Presentacion extends javax.swing.JFrame {
    private Timer timer;
    /**
     * Creates new form Presentacion
     */
    public Presentacion() {
        initComponents();
        this.setLocationRelativeTo(null);   
    }
    String contenido [] = {"Cargando Modulos...","Cargando Complementos...","Cargando Formularios...","Inicializando..."};
    int c = 0;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pginicio = new javax.swing.JProgressBar();
        lbcontenido = new javax.swing.JLabel();
        lbimagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pginicio.setStringPainted(true);
        getContentPane().add(pginicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 526, -1));

        lbcontenido.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lbcontenido.setText(" ");
        getContentPane().add(lbcontenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 490, -1));

        lbimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/rsz_sdmtlogo.jpg"))); // NOI18N
        lbimagen.setText(" ");
        getContentPane().add(lbimagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 526, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        LoginTimer();
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Presentacion().setVisible(true);
            }
        });
    }
    public void ProgressBar(){
        int n = pginicio.getValue();
           if(n < 100){
                if((n % 25) == 0){
                   lbcontenido.setText(contenido[c]);
                   c++;
                }
                n++;
                pginicio.setValue(n); 
            }
           else{
               timer.stop();
               this.setVisible(false);
               new Login().setVisible(true);
           }
    }
    
    ActionListener al = new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent e) {
            ProgressBar();
            
        }
    };
    
    public void LoginTimer(){
        timer = new Timer(250,al);
        timer.start();
    }
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel lbcontenido;
    private javax.swing.JLabel lbimagen;
    public static javax.swing.JProgressBar pginicio;
    // End of variables declaration//GEN-END:variables
}
