/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios.Mantenimiento;


import javax.swing.JOptionPane;
import libraries.formularios.dbEmpleados;
import libraries.formularios.libValidacionesTexto;

/**
 *
 * @author Ellet
 */
public class MantenimientoEmpleados extends javax.swing.JFrame {

    
    
    public MantenimientoEmpleados() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        lbidempleado.setVisible(false);
        txtidempleado.setVisible(false);
        this.setResizable(false);
        new dbEmpleados().CargarCargos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        txtcedula = new javax.swing.JTextField();
        cbcargo = new javax.swing.JComboBox<>();
        lbiduser = new javax.swing.JLabel();
        txtiduser = new javax.swing.JTextField();
        botoncancelar = new javax.swing.JButton();
        botonnuevo = new javax.swing.JButton();
        txtfechanacimiento = new com.toedter.calendar.JDateChooser();
        botonrealizarconsulta = new javax.swing.JButton();
        botonmodificar = new javax.swing.JButton();
        botoneliminar = new javax.swing.JButton();
        botonconsultar = new javax.swing.JButton();
        botonguardar = new javax.swing.JButton();
        txtidempleado = new javax.swing.JTextField();
        lbidempleado = new javax.swing.JLabel();
        lbimagenfondo = new javax.swing.JLabel();

        setTitle("MANTENIMIENTO EMPLEADOS");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel1.setText("MANTENIMIENTO EMPLEADOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel2.setText("NOMBRES:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel3.setText("APELLIDOS:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 194, -1, -1));

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel4.setText("CODIGO:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 72, -1, -1));

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel5.setText("FECHA DE NACIMIENTO:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel6.setText("CEDULA:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 112, -1, -1));

        jLabel7.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel7.setText("DIRECCION:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 271, -1, -1));

        jLabel8.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel8.setText("TELEFONO:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 308, -1, -1));

        jLabel9.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel9.setText("CARGO:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 346, -1, -1));

        txtcodigo.setEnabled(false);
        txtcodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodigoKeyTyped(evt);
            }
        });
        getContentPane().add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 70, 117, -1));

        txtnombre.setEnabled(false);
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 148, 117, -1));

        txtapellido.setEnabled(false);
        txtapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapellidoActionPerformed(evt);
            }
        });
        txtapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapellidoKeyTyped(evt);
            }
        });
        getContentPane().add(txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 192, 117, -1));

        txttelefono.setEnabled(false);
        txttelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 306, 117, -1));

        txtdireccion.setEnabled(false);
        txtdireccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtdireccionMouseClicked(evt);
            }
        });
        txtdireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdireccionKeyTyped(evt);
            }
        });
        getContentPane().add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 268, 117, -1));

        txtcedula.setEnabled(false);
        txtcedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcedulaFocusLost(evt);
            }
        });
        txtcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcedulaActionPerformed(evt);
            }
        });
        txtcedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcedulaKeyTyped(evt);
            }
        });
        getContentPane().add(txtcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 110, 117, -1));

        cbcargo.setEnabled(false);
        getContentPane().add(cbcargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 344, 117, -1));

        lbiduser.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lbiduser.setText("ID USER:");
        getContentPane().add(lbiduser, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 384, -1, -1));

        txtiduser.setEditable(false);
        txtiduser.setEnabled(false);
        txtiduser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtiduserMouseClicked(evt);
            }
        });
        getContentPane().add(txtiduser, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 382, 117, -1));

        botoncancelar.setText("CANCELAR");
        botoncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncancelarActionPerformed(evt);
            }
        });
        getContentPane().add(botoncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 568, 140, 40));

        botonnuevo.setText("NUEVO");
        botonnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonnuevoActionPerformed(evt);
            }
        });
        getContentPane().add(botonnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 452, 146, 40));

        txtfechanacimiento.setEnabled(false);
        txtfechanacimiento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfechanacimientoFocusLost(evt);
            }
        });
        getContentPane().add(txtfechanacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 230, 117, -1));

        botonrealizarconsulta.setText("...");
        botonrealizarconsulta.setEnabled(false);
        botonrealizarconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonrealizarconsultaActionPerformed(evt);
            }
        });
        getContentPane().add(botonrealizarconsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 69, 31, -1));

        botonmodificar.setText("MODIFICAR");
        botonmodificar.setEnabled(false);
        botonmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonmodificarActionPerformed(evt);
            }
        });
        getContentPane().add(botonmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 510, -1, 40));

        botoneliminar.setText("ELIMINAR");
        botoneliminar.setEnabled(false);
        botoneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoneliminarActionPerformed(evt);
            }
        });
        getContentPane().add(botoneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 510, 92, 40));

        botonconsultar.setText("CONSULTAR");
        botonconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonconsultarActionPerformed(evt);
            }
        });
        getContentPane().add(botonconsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 452, 146, 40));

        botonguardar.setText("GUARDAR");
        botonguardar.setEnabled(false);
        botonguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonguardarActionPerformed(evt);
            }
        });
        getContentPane().add(botonguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 510, 90, 40));

        txtidempleado.setEditable(false);
        txtidempleado.setEnabled(false);
        txtidempleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtidempleadoMouseClicked(evt);
            }
        });
        getContentPane().add(txtidempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 420, 117, -1));

        lbidempleado.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lbidempleado.setText("ID EMPLEADO:");
        getContentPane().add(lbidempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 422, -1, -1));

        lbimagenfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/rsz_mantenimiento.jpg"))); // NOI18N
        lbimagenfondo.setText(" ");
        getContentPane().add(lbimagenfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidoActionPerformed

    private void txtcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcedulaActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void botoneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoneliminarActionPerformed
        if(new dbEmpleados().ValidacionEspaciosEliminar()){
            JOptionPane.showMessageDialog(null, "DEBE LLENAR LA ID DEL EMPLEADO A ELIMINAR", "WARNING",JOptionPane.ERROR_MESSAGE);
        }
        else{
            DeshabilitarCampos();
            new dbEmpleados().EliminarRegistros();
            botonnuevo.setEnabled(true);
            botonconsultar.setEnabled(true);
            botonrealizarconsulta.setEnabled(false);
            botonmodificar.setEnabled(false);
            botoneliminar.setEnabled(false);
            botonguardar.setEnabled(false);
            new dbEmpleados().Limpiar();
        }
        
    }//GEN-LAST:event_botoneliminarActionPerformed

    private void botonguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonguardarActionPerformed
        if(new dbEmpleados().ValidacionEspaciosGuardar()){
            JOptionPane.showMessageDialog(null, "DEBE LLENAR TODOS LOS DATOS", "WARNING",JOptionPane.ERROR_MESSAGE);
        }
        else{
            DeshabilitarCampos();
            new dbEmpleados().IngresarIdentidades();
            botonnuevo.setEnabled(true);
            botonconsultar.setEnabled(true);
            botonrealizarconsulta.setEnabled(false);
            botonmodificar.setEnabled(false);
            botoneliminar.setEnabled(false);
            botonguardar.setEnabled(false);
            new dbEmpleados().Limpiar();
        }
        
    }//GEN-LAST:event_botonguardarActionPerformed

    private void botoncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncancelarActionPerformed
        this.setVisible(false);
        
    }//GEN-LAST:event_botoncancelarActionPerformed

    private void botonnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonnuevoActionPerformed
        botonguardar.setEnabled(true);
        botonrealizarconsulta.setEnabled(false);
        lbiduser.setVisible(true);
        lbidempleado.setVisible(false);
        botonmodificar.setEnabled(false);
        botoneliminar.setEnabled(false);
        txtidempleado.setVisible(false);
        txtiduser.setVisible(true);
        botonnuevo.setEnabled(false);
        botonconsultar.setEnabled(true);       
        HabilitarCampos();
        new dbEmpleados().Limpiar();

    }//GEN-LAST:event_botonnuevoActionPerformed

    private void botonconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonconsultarActionPerformed
        botonguardar.setEnabled(false);
        botonrealizarconsulta.setEnabled(true);
        botonmodificar.setEnabled(true);
        botoneliminar.setEnabled(true);
        lbiduser.setVisible(true);
        txtiduser.setVisible(true);
        lbidempleado.setVisible(true);
        txtidempleado.setVisible(true);
        botonnuevo.setEnabled(true);
        botonconsultar.setEnabled(false);
        HabilitarCampos();
        new dbEmpleados().Limpiar();

    }//GEN-LAST:event_botonconsultarActionPerformed

    private void txtiduserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtiduserMouseClicked
        if(txtiduser.isEnabled()){
            new MantenimientoUsuarios().setVisible(true);
            MantenimientoUsuarios.botoncancelar.setEnabled(false);
        }
        
    }//GEN-LAST:event_txtiduserMouseClicked

    private void txtidempleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtidempleadoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidempleadoMouseClicked

    private void botonrealizarconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonrealizarconsultaActionPerformed
        if(txtcodigo.getText().replaceAll("\\s","").equals("")){
            JOptionPane.showMessageDialog(null, "PORFAVOR LLENE PARAMETRO DE BUSQUEDA","WARNING",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            new dbEmpleados().ConsultarRegistros();
        }
        
        
    }//GEN-LAST:event_botonrealizarconsultaActionPerformed

    private void botonmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonmodificarActionPerformed
         if(new dbEmpleados().ValidacionEspaciosModificar()){
            JOptionPane.showMessageDialog(null, "DEBE LLENAR TODOS LOS DATOS", "WARNING",JOptionPane.ERROR_MESSAGE);
        }
        else{
             DeshabilitarCampos();
            new dbEmpleados().ModificarIdentidades();
            botonnuevo.setEnabled(true);
            botonconsultar.setEnabled(true);
            botonrealizarconsulta.setEnabled(false);
            botonmodificar.setEnabled(false);
            botoneliminar.setEnabled(false);
            botonguardar.setEnabled(false);
            new dbEmpleados().Limpiar();
        }
        
    }//GEN-LAST:event_botonmodificarActionPerformed

    private void txtcedulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcedulaFocusLost
        if(new libValidacionesTexto().ValidarLongitudMinimaCedula(txtcedula.getText().length())){
            txtcedula.requestFocus();
        }
        
       
    }//GEN-LAST:event_txtcedulaFocusLost

    private void txtcodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoKeyTyped
        new libValidacionesTexto().ValidacionesCodigoEmpleado(evt, txtcodigo.getText().length());
        new libValidacionesTexto().ValidarLetrasYNumeros(evt);
    }//GEN-LAST:event_txtcodigoKeyTyped

    private void txtcedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcedulaKeyTyped
        new libValidacionesTexto().ValidacionNumerica(evt);
        new libValidacionesTexto().ValidarLongitudCedula(evt, txtcedula.getText().length());
    }//GEN-LAST:event_txtcedulaKeyTyped

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
        new libValidacionesTexto().ValidacionesCaracteresEspeciales(evt);
    }//GEN-LAST:event_txtnombreKeyTyped

    private void txtdireccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdireccionMouseClicked
        
        
    }//GEN-LAST:event_txtdireccionMouseClicked

    private void txtfechanacimientoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfechanacimientoFocusLost
        
    }//GEN-LAST:event_txtfechanacimientoFocusLost

    private void txtapellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidoKeyTyped
        new libValidacionesTexto().ValidacionesCaracteresEspeciales(evt);
    }//GEN-LAST:event_txtapellidoKeyTyped

    private void txtdireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccionKeyTyped
        new libValidacionesTexto().ValidarLetrasYNumeros(evt);
    }//GEN-LAST:event_txtdireccionKeyTyped

    private void txttelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoKeyTyped
        new libValidacionesTexto().ValidacionNumerica(evt);
    }//GEN-LAST:event_txttelefonoKeyTyped

    public void HabilitarCampos(){
        txtcodigo.setEnabled(true);
        txtcedula.setEnabled(true);
        txtnombre.setEnabled(true);
        txtapellido.setEnabled(true);
        txtfechanacimiento.setEnabled(true);
        txtdireccion.setEnabled(true);
        txttelefono.setEnabled(true);
        cbcargo.setEnabled(true);
        txtidempleado.setEnabled(true);
        txtiduser.setEnabled(true);
        
        
        
        
    }
    public void DeshabilitarCampos(){
        txtcodigo.setEnabled(false);
        txtcedula.setEnabled(false);
        txtnombre.setEnabled(false);
        txtapellido.setEnabled(false);
        txtfechanacimiento.setEnabled(false);
        txtdireccion.setEnabled(false);
        txttelefono.setEnabled(false);
        cbcargo.setEnabled(false);
        txtidempleado.setEnabled(false);
        txtiduser.setEnabled(false);
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantenimientoEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantenimientoEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantenimientoEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantenimientoEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MantenimientoEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoncancelar;
    private javax.swing.JButton botonconsultar;
    private javax.swing.JButton botoneliminar;
    private javax.swing.JButton botonguardar;
    private javax.swing.JButton botonmodificar;
    private javax.swing.JButton botonnuevo;
    private javax.swing.JButton botonrealizarconsulta;
    public static javax.swing.JComboBox<String> cbcargo;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jLabel9;
    public static javax.swing.JLabel lbidempleado;
    public static javax.swing.JLabel lbiduser;
    private javax.swing.JLabel lbimagenfondo;
    public static javax.swing.JTextField txtapellido;
    public static javax.swing.JTextField txtcedula;
    public static javax.swing.JTextField txtcodigo;
    public static javax.swing.JTextField txtdireccion;
    public static com.toedter.calendar.JDateChooser txtfechanacimiento;
    public static javax.swing.JTextField txtidempleado;
    public static javax.swing.JTextField txtiduser;
    public static javax.swing.JTextField txtnombre;
    public static javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
