/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios.Mantenimiento;

import Formularios.Principal.Principal;
import javax.swing.JOptionPane;
import libraries.formularios.dbUsers;
import libraries.formularios.libValidacionesTexto;

/**
 *
 * @author Ellet
 */
public class MantenimientoUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form AgregarUsuario
     */
    public MantenimientoUsuarios() {
        initComponents();
        this.setLocationRelativeTo(null);
        lbiduser.setVisible(false);
        txtiduser.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        cbnivel = new javax.swing.JComboBox<>();
        txtpassword = new javax.swing.JPasswordField();
        botonregresar = new javax.swing.JButton();
        botonmodificar = new javax.swing.JButton();
        botoneliminar = new javax.swing.JButton();
        botonconsultar = new javax.swing.JButton();
        botonguardar = new javax.swing.JButton();
        botonnuevo = new javax.swing.JButton();
        botonrealizarconsulta = new javax.swing.JButton();
        lbiduser = new javax.swing.JLabel();
        txtiduser = new javax.swing.JTextField();
        botoncancelar = new javax.swing.JButton();
        lbimagenfondo = new javax.swing.JLabel();

        setTitle("MANTENIMIENTO USUARIO");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel1.setText("MANTENIMIENTO USUARIOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel2.setText("USERNAME:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 74, -1, -1));

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel3.setText("PASSWORD:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 115, -1, -1));

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel4.setText("NIVEL:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 159, -1, -1));

        txtusername.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtusername.setEnabled(false);
        txtusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtusernameKeyTyped(evt);
            }
        });
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 71, 143, -1));

        cbnivel.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        cbnivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USUARIO", "ADMINISTRADOR", "SUPERUSUARIO" }));
        cbnivel.setSelectedIndex(-1);
        cbnivel.setEnabled(false);
        getContentPane().add(cbnivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 156, 143, -1));

        txtpassword.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtpassword.setEnabled(false);
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        txtpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpasswordKeyTyped(evt);
            }
        });
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 112, 143, -1));

        botonregresar.setText("REGRESAR");
        botonregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonregresarActionPerformed(evt);
            }
        });
        getContentPane().add(botonregresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 360, 108, 46));

        botonmodificar.setText("MODIFICAR");
        botonmodificar.setEnabled(false);
        botonmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonmodificarActionPerformed(evt);
            }
        });
        getContentPane().add(botonmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 302, -1, 40));

        botoneliminar.setText("ELIMINAR");
        botoneliminar.setEnabled(false);
        botoneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoneliminarActionPerformed(evt);
            }
        });
        getContentPane().add(botoneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 302, 92, 40));

        botonconsultar.setText("CONSULTAR");
        botonconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonconsultarActionPerformed(evt);
            }
        });
        getContentPane().add(botonconsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 244, 146, 40));

        botonguardar.setText("GUARDAR");
        botonguardar.setEnabled(false);
        botonguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonguardarActionPerformed(evt);
            }
        });
        getContentPane().add(botonguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 302, 90, 40));

        botonnuevo.setText("NUEVO");
        botonnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonnuevoActionPerformed(evt);
            }
        });
        getContentPane().add(botonnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 244, 146, 40));

        botonrealizarconsulta.setText("...");
        botonrealizarconsulta.setEnabled(false);
        botonrealizarconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonrealizarconsultaActionPerformed(evt);
            }
        });
        getContentPane().add(botonrealizarconsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 71, 31, -1));

        lbiduser.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lbiduser.setText("ID USER:");
        getContentPane().add(lbiduser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 199, -1, -1));

        txtiduser.setEditable(false);
        txtiduser.setEnabled(false);
        txtiduser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtiduserMouseClicked(evt);
            }
        });
        getContentPane().add(txtiduser, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 197, 143, -1));

        botoncancelar.setText("CANCELAR");
        botoncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncancelarActionPerformed(evt);
            }
        });
        getContentPane().add(botoncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 363, 108, 40));

        lbimagenfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/rsz_2mantenimiento.jpg"))); // NOI18N
        lbimagenfondo.setText(" ");
        getContentPane().add(lbimagenfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botoneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoneliminarActionPerformed
        if(new dbUsers().ValidacionesEspaciosEliminar()){
            JOptionPane.showMessageDialog(null, "DEBE LLENAR LA ID DEL USUARIO A ELIMINAR", "WARNING",JOptionPane.ERROR_MESSAGE);
        }
        else{
             new dbUsers().EliminarRegistros();
            DeshabilitarCampos();
            botonnuevo.setEnabled(true);
            botonconsultar.setEnabled(true);
            botonrealizarconsulta.setEnabled(false);
            botonmodificar.setEnabled(false);
            botoneliminar.setEnabled(false);
            botonguardar.setEnabled(false);
            new dbUsers().Limpiar();
        }
       
       
    }//GEN-LAST:event_botoneliminarActionPerformed

    private void botonconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonconsultarActionPerformed
        botonguardar.setEnabled(false);
        botonrealizarconsulta.setEnabled(true);
        botonmodificar.setEnabled(true);
        botoneliminar.setEnabled(true);
        lbiduser.setVisible(true);
        txtiduser.setVisible(true);
        HabilitarCampos();
        new dbUsers().Limpiar();
    }//GEN-LAST:event_botonconsultarActionPerformed

    private void botonguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonguardarActionPerformed
        if(new dbUsers().ValidacionesEspaciosGuardar()){
            JOptionPane.showMessageDialog(null, "DEBE LLENAR TODOS LOS DATOS", "WARNING",JOptionPane.ERROR_MESSAGE);
        }
        else{
            new dbUsers().IngresarIdentidades();
            int e = new dbUsers().CargarIdUser();
            if(e != -1 && botonregresar.isEnabled()){
            MantenimientoEmpleados.txtiduser.setText(Integer.toString(e));
            }
            botonnuevo.setEnabled(true);
            botonrealizarconsulta.setEnabled(false);
            botonmodificar.setEnabled(false);
            botoneliminar.setEnabled(false);
            botonguardar.setEnabled(false);
            botonconsultar.setEnabled(true);
            new dbUsers().Limpiar();
        }
                
        
      
    }//GEN-LAST:event_botonguardarActionPerformed

    private void botonnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonnuevoActionPerformed
        botonguardar.setEnabled(true);
        botonrealizarconsulta.setEnabled(false);
        botonmodificar.setEnabled(false);
        botoneliminar.setEnabled(false);
        lbiduser.setVisible(false);
        txtiduser.setVisible(false);
        HabilitarCampos();
        new dbUsers().Limpiar();
    }//GEN-LAST:event_botonnuevoActionPerformed

    private void txtiduserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtiduserMouseClicked
       
    }//GEN-LAST:event_txtiduserMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
    }//GEN-LAST:event_formWindowClosing

    private void botonmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonmodificarActionPerformed
        if(new dbUsers().ValidacionesEspaciosModificar()){
            JOptionPane.showMessageDialog(null, "DEBE LLENAR TODOS LOS DATOS", "WARNING",JOptionPane.ERROR_MESSAGE);
        }
        else{
            new dbUsers().ModificarIdentidades();
            DeshabilitarCampos();
            botonrealizarconsulta.setEnabled(false);
            botonmodificar.setEnabled(false);
            botoneliminar.setEnabled(false);
            botonguardar.setEnabled(false);
            botonnuevo.setEnabled(true);
            botonconsultar.setEnabled(true);
            new dbUsers().Limpiar();
        }
        
        
        
    }//GEN-LAST:event_botonmodificarActionPerformed

    private void botonregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonregresarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_botonregresarActionPerformed

    private void botoncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncancelarActionPerformed
        this.setVisible(false);
        
    }//GEN-LAST:event_botoncancelarActionPerformed

    private void botonrealizarconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonrealizarconsultaActionPerformed
        if(txtusername.getText().replaceAll("\\s","").equals("")){
            JOptionPane.showMessageDialog(null, "PORFAVOR LLENE PARAMETRO DE BUSQUEDA","WARNING",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            new dbUsers().ConsultarRegistros();
        }
        
    }//GEN-LAST:event_botonrealizarconsultaActionPerformed

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void txtusernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusernameKeyTyped
        new libValidacionesTexto().ValidarLongitudUsuarios(evt, txtusername.getText().length());
        
    }//GEN-LAST:event_txtusernameKeyTyped

    private void txtpasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyTyped
         new libValidacionesTexto().ValidarLongitudUsuarios(evt, new String(txtpassword.getPassword()).length());
    }//GEN-LAST:event_txtpasswordKeyTyped
    
    public void HabilitarCampos(){
        txtusername.setEnabled(true);
        txtpassword.setEnabled(true);
        cbnivel.setEnabled(true);
        txtiduser.setEnabled(true);
               
    }
    
    public void DeshabilitarCampos(){
        txtusername.setEnabled(false);
        txtpassword.setEnabled(false);
        cbnivel.setEnabled(false);
        txtiduser.setEnabled(false);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantenimientoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantenimientoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantenimientoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantenimientoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MantenimientoUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton botoncancelar;
    private javax.swing.JButton botonconsultar;
    private javax.swing.JButton botoneliminar;
    private javax.swing.JButton botonguardar;
    private javax.swing.JButton botonmodificar;
    private javax.swing.JButton botonnuevo;
    private javax.swing.JButton botonrealizarconsulta;
    public static javax.swing.JButton botonregresar;
    public static javax.swing.JComboBox<String> cbnivel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel lbiduser;
    private javax.swing.JLabel lbimagenfondo;
    public static javax.swing.JTextField txtiduser;
    public static javax.swing.JPasswordField txtpassword;
    public static javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
