/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios.Mantenimiento;

import javax.swing.JOptionPane;
import libraries.formularios.dbProveedores;
import libraries.formularios.libValidacionesTexto;
import libraries.identidades.IdentidadesProveedores;
import repositorio.repositorio_proveedores;

/**
 *
 * @author Ellet
 */
public class MantenimientoProveedores extends javax.swing.JFrame {
    repositorio_proveedores repro = new repositorio_proveedores();
    /**
     * Creates new form MantenimientoProveedores
     */
    public MantenimientoProveedores() {
        initComponents();
        this.setLocationRelativeTo(null);
        lbidproveedores.setVisible(false);
        txtidproveedores.setVisible(false);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbidproveedores = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtidproveedores = new javax.swing.JTextField();
        cbtipo = new javax.swing.JComboBox<>();
        botoncancelar = new javax.swing.JButton();
        botonnuevo = new javax.swing.JButton();
        botonmodificar = new javax.swing.JButton();
        botoneliminar = new javax.swing.JButton();
        botonconsultar = new javax.swing.JButton();
        botonguardar = new javax.swing.JButton();
        botonrealizarconsulta = new javax.swing.JButton();
        lbimagenfondo = new javax.swing.JLabel();

        setTitle("MANTENIMIENTO PROVEEDORES");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel1.setText("CODIGO:");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 76, -1, -1));

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel2.setText("MANTENIMIENTO PROVEEDORES");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 19, -1, -1));

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel3.setText("TIPO:");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 154, -1, -1));

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel4.setText("NOMBRE:");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 116, -1, -1));

        lbidproveedores.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lbidproveedores.setText("ID PROVEEDORES:");
        lbidproveedores.setToolTipText("");
        getContentPane().add(lbidproveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        txtcodigo.setEnabled(false);
        txtcodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodigoKeyTyped(evt);
            }
        });
        getContentPane().add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 74, 124, -1));

        txtnombre.setEnabled(false);
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 114, 124, -1));

        txtidproveedores.setEnabled(false);
        getContentPane().add(txtidproveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 190, 61, -1));

        cbtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHIP", "RECARGA" }));
        cbtipo.setSelectedIndex(-1);
        cbtipo.setEnabled(false);
        getContentPane().add(cbtipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 152, 124, -1));

        botoncancelar.setText("CANCELAR");
        botoncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncancelarActionPerformed(evt);
            }
        });
        getContentPane().add(botoncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 381, 140, 40));

        botonnuevo.setText("NUEVO");
        botonnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonnuevoActionPerformed(evt);
            }
        });
        getContentPane().add(botonnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 265, 146, 40));

        botonmodificar.setText("MODIFICAR");
        botonmodificar.setEnabled(false);
        botonmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonmodificarActionPerformed(evt);
            }
        });
        getContentPane().add(botonmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 323, -1, 40));

        botoneliminar.setText("ELIMINAR");
        botoneliminar.setEnabled(false);
        botoneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoneliminarActionPerformed(evt);
            }
        });
        getContentPane().add(botoneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 323, 92, 40));

        botonconsultar.setText("CONSULTAR");
        botonconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonconsultarActionPerformed(evt);
            }
        });
        getContentPane().add(botonconsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 265, 146, 40));

        botonguardar.setText("GUARDAR");
        botonguardar.setEnabled(false);
        botonguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonguardarActionPerformed(evt);
            }
        });
        getContentPane().add(botonguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 323, 90, 40));

        botonrealizarconsulta.setText("...");
        botonrealizarconsulta.setEnabled(false);
        botonrealizarconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonrealizarconsultaActionPerformed(evt);
            }
        });
        getContentPane().add(botonrealizarconsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 73, 31, -1));

        lbimagenfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/rsz_1mantenimiento.jpg"))); // NOI18N
        lbimagenfondo.setText(" ");
        getContentPane().add(lbimagenfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void botoncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_botoncancelarActionPerformed

    private void botonnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonnuevoActionPerformed
        botonguardar.setEnabled(true);
        botonrealizarconsulta.setEnabled(false);
        botonmodificar.setEnabled(false);
        botoneliminar.setEnabled(false);
        lbidproveedores.setVisible(false);
        txtidproveedores.setVisible(false);
        HabilitarCampos();
        botonnuevo.setEnabled(false);
        botonconsultar.setEnabled(true);
        repro.Limpiar();
    }//GEN-LAST:event_botonnuevoActionPerformed

    private void botoneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoneliminarActionPerformed
        if(repro.ValidacionEspaciosEliminar()){
            JOptionPane.showMessageDialog(null, "DEBE LLENAR LA ID DEL PROVEEDOR A ELIMINAR", "WARNING",JOptionPane.ERROR_MESSAGE);
        }else{
            repro.EliminarRegistros();
            DeshabilitarCampos();
            repro.Limpiar();
            botonguardar.setEnabled(false);
            botonmodificar.setEnabled(false);
            botoneliminar.setEnabled(false);
            botonnuevo.setEnabled(true);
            botonconsultar.setEnabled(true);
        }
        
    }//GEN-LAST:event_botoneliminarActionPerformed

    private void botonconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonconsultarActionPerformed
        botonguardar.setEnabled(false);
        botonrealizarconsulta.setEnabled(true);
        botonmodificar.setEnabled(true);
        botoneliminar.setEnabled(true);
        lbidproveedores.setVisible(true);
        txtidproveedores.setVisible(true);
        HabilitarCampos();
        botonconsultar.setEnabled(false);
        botonnuevo.setEnabled(true);
        repro.Limpiar();
    }//GEN-LAST:event_botonconsultarActionPerformed

    private void botonguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonguardarActionPerformed
        if(repro.ValidacionEspaciosGuardar()){
            JOptionPane.showMessageDialog(null, "DEBE LLENAR TODOS LOS DATOS", "WARNING",JOptionPane.ERROR_MESSAGE);
        }
        else{
            IdentidadesProveedores id = new IdentidadesProveedores(txtcodigo.getText(),txtnombre.getText(), cbtipo.getSelectedItem().toString());
            repro.IngresarRegistros(id);
            DeshabilitarCampos();
            repro.Limpiar();
            botonguardar.setEnabled(false);
            botonmodificar.setEnabled(false);
            botoneliminar.setEnabled(false);
            botonnuevo.setEnabled(true);
            botonconsultar.setEnabled(true);
        }
        
    }//GEN-LAST:event_botonguardarActionPerformed

    private void botonmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonmodificarActionPerformed
        if(repro.ValidacionEspaciosModificar()){
            JOptionPane.showMessageDialog(null, "DEBE LLENAR TODOS LOS DATOS", "WARNING",JOptionPane.ERROR_MESSAGE);
        }
        else{
            IdentidadesProveedores id = new IdentidadesProveedores(Integer.parseInt(txtidproveedores.getText()),txtcodigo.getText(),txtnombre.getText(), cbtipo.getSelectedItem().toString());
            repro.ModificarRegistros(id);
            DeshabilitarCampos();
            repro.Limpiar();
            botonguardar.setEnabled(false);
            botonmodificar.setEnabled(false);
            botoneliminar.setEnabled(false);
            botonnuevo.setEnabled(true);
            botonconsultar.setEnabled(true);
        }
        
        
    }//GEN-LAST:event_botonmodificarActionPerformed

    private void botonrealizarconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonrealizarconsultaActionPerformed
        if(txtcodigo.getText().replaceAll("\\s","").equals("")){
            JOptionPane.showMessageDialog(null, "PORFAVOR LLENE PARAMETRO DE BUSQUEDA","WARNING",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            IdentidadesProveedores id = repro.ConsultarRegistro();
            txtidproveedores.setText(Integer.toString(id.getId_proveedores()));
            txtcodigo.setText(id.getCodigo_proveedores());
            txtnombre.setText(id.getNombre_proveedores());
            cbtipo.setSelectedItem(id.getTipo_producto());
        }
        
        
    }//GEN-LAST:event_botonrealizarconsultaActionPerformed

    private void txtcodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoKeyTyped
        new libValidacionesTexto().ValidarLetrasYNumeros(evt);
    }//GEN-LAST:event_txtcodigoKeyTyped

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
        new libValidacionesTexto().ValidacionesCaracteresEspeciales(evt);
    }//GEN-LAST:event_txtnombreKeyTyped
    
    public void HabilitarCampos(){
        txtcodigo.setEnabled(true);
        txtnombre.setEnabled(true);
        cbtipo.setEnabled(true);
        
        
    }
    
    public void DeshabilitarCampos(){
        txtcodigo.setEnabled(false);
        txtnombre.setEnabled(false);
        cbtipo.setEnabled(false);
        
    }
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantenimientoProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantenimientoProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantenimientoProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantenimientoProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MantenimientoProveedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoncancelar;
    private javax.swing.JButton botonconsultar;
    private javax.swing.JButton botoneliminar;
    private javax.swing.JButton botonguardar;
    private javax.swing.JButton botonmodificar;
    private javax.swing.JButton botonnuevo;
    private javax.swing.JButton botonrealizarconsulta;
    public static javax.swing.JComboBox<String> cbtipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbidproveedores;
    private javax.swing.JLabel lbimagenfondo;
    public static javax.swing.JTextField txtcodigo;
    public static javax.swing.JTextField txtidproveedores;
    public static javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
